### ISSUE TITLE
very like goa 

### ISSUE THREAD

**Issue by joe-getcouragenow** [golangee/architecture#1]
From the test files it very goa like

https://github.com/goadesign

**Comment by torbenschinke** [comment]
Yes, it looks like old wine in new bottles. However, I think there are a few things, which could be solved better and these are very important for me. For example, the DSL of goa is really awkward and one gets no support by the compiler, just runtime errors. Thus, also autocompletion is of no help. The generated diagrams and markdown documents do not fulfill my expectations either. Also, the generated code structure does not scale well for larger projects. Last but not least, the code generation is bound to Go only.

In the end there is just too much I disagree with. Currently, I'm still designing all moving parts and the generators are not even capable of producing a runnable application. But lets see, if I can find a satisfying solution for this ;-)
